import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlmodel import SQLModel, Field


class Model3D(SQLModel, table=True):
    __tablename__ = "models"

    id: str = Field(default_factory=lambda: str(uuid.uuid4()), primary_key=True)
    name: str
    description: str = ""
    category: str = ""  # muqarnas, arches, domes, geometric_patterns, mashrabiya, other
    source: str = ""  # "builtin", "uploaded", "generated"
    license: str = ""
    file_path: str  # relative path to glTF/OBJ file
    original_format: str = ""  # obj, gltf, stl, glb
    thumbnail_path: Optional[str] = None
    vertex_count: int = 0
    face_count: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # If this model was generated by a job
    source_job_id: Optional[str] = None
